/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import {
  ModelGetOptionalParams,
  ModelGetResponse,
  ModelDeleteOptionalParams,
  ModelDeleteResponse
} from "../models";

/** Interface representing a Model. */
export interface Model {
  /**
   * @param modelId
   * @param options The options parameters.
   */
  get(
    modelId: string,
    options?: ModelGetOptionalParams
  ): Promise<ModelGetResponse>;
  /**
   * @param modelId
   * @param options The options parameters.
   */
  delete(
    modelId: string,
    options?: ModelDeleteOptionalParams
  ): Promise<ModelDeleteResponse>;
}
