/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import {
  OperationsGetOperationsPageOptionalParams,
  OperationsGetOperationsPageResponse,
  OperationsGetOperationOptionalParams,
  OperationsGetOperationOperationResponse
} from "../models";

/** Interface representing a Operations. */
export interface Operations {
  /** @param options The options parameters. */
  getOperationsPage(
    options?: OperationsGetOperationsPageOptionalParams
  ): Promise<OperationsGetOperationsPageResponse>;
  /**
   * @param operationId
   * @param options The options parameters.
   */
  getOperation(
    operationId: string,
    options?: OperationsGetOperationOptionalParams
  ): Promise<OperationsGetOperationOperationResponse>;
}
