// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace FormRecognizerClient.Models
{
    /// <summary> The Components1MheujySchemasModelsAnalyzeresultsDocumentelementsObjectfieldPropertiesValueobjectAdditionalproperties. </summary>
    internal partial class Components1MheujySchemasModelsAnalyzeresultsDocumentelementsObjectfieldPropertiesValueobjectAdditionalproperties
    {
        /// <summary> Initializes a new instance of Components1MheujySchemasModelsAnalyzeresultsDocumentelementsObjectfieldPropertiesValueobjectAdditionalproperties. </summary>
        internal Components1MheujySchemasModelsAnalyzeresultsDocumentelementsObjectfieldPropertiesValueobjectAdditionalproperties()
        {
        }
    }
}
