// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using System.Linq;
using Azure.Core;

namespace FormRecognizerClient.Models
{
    /// <summary> The ComposeModelRequest. </summary>
    public partial class ComposeModelRequest
    {
        /// <summary> Initializes a new instance of ComposeModelRequest. </summary>
        /// <param name="modelId"></param>
        /// <param name="componentModels"></param>
        /// <exception cref="ArgumentNullException"> <paramref name="modelId"/> or <paramref name="componentModels"/> is null. </exception>
        public ComposeModelRequest(string modelId, IEnumerable<ComponentModelInfo> componentModels)
        {
            if (modelId == null)
            {
                throw new ArgumentNullException(nameof(modelId));
            }
            if (componentModels == null)
            {
                throw new ArgumentNullException(nameof(componentModels));
            }

            ModelId = modelId;
            ComponentModels = componentModels.ToList();
            Tags = new ChangeTrackingDictionary<string, string>();
        }

        /// <summary> Gets the model id. </summary>
        public string ModelId { get; }
        /// <summary> Gets or sets the description. </summary>
        public string Description { get; set; }
        /// <summary> Gets the component models. </summary>
        public IList<ComponentModelInfo> ComponentModels { get; }
        /// <summary> Dictionary of &lt;string&gt;. </summary>
        public IDictionary<string, string> Tags { get; }
    }
}
