// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace FormRecognizerClient.Models
{
    /// <summary> The CustomDocumentModelInfo. </summary>
    public partial class CustomDocumentModelInfo
    {
        /// <summary> Initializes a new instance of CustomDocumentModelInfo. </summary>
        /// <param name="count"></param>
        /// <param name="limit"></param>
        internal CustomDocumentModelInfo(int count, int limit)
        {
            Count = count;
            Limit = limit;
        }

        /// <summary> Gets the count. </summary>
        public int Count { get; }
        /// <summary> Gets the limit. </summary>
        public int Limit { get; }
    }
}
