// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.ComponentModel;

namespace FormRecognizerClient.Models
{
    /// <summary> The ModelsAnalyzeResultsDocumentElementsCurrencyFieldType. </summary>
    internal readonly partial struct ModelsAnalyzeResultsDocumentElementsCurrencyFieldType : IEquatable<ModelsAnalyzeResultsDocumentElementsCurrencyFieldType>
    {
        private readonly string _value;

        /// <summary> Initializes a new instance of <see cref="ModelsAnalyzeResultsDocumentElementsCurrencyFieldType"/>. </summary>
        /// <exception cref="ArgumentNullException"> <paramref name="value"/> is null. </exception>
        public ModelsAnalyzeResultsDocumentElementsCurrencyFieldType(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        private const string CurrencyValue = "currency";

        /// <summary> currency. </summary>
        public static ModelsAnalyzeResultsDocumentElementsCurrencyFieldType Currency { get; } = new ModelsAnalyzeResultsDocumentElementsCurrencyFieldType(CurrencyValue);
        /// <summary> Determines if two <see cref="ModelsAnalyzeResultsDocumentElementsCurrencyFieldType"/> values are the same. </summary>
        public static bool operator ==(ModelsAnalyzeResultsDocumentElementsCurrencyFieldType left, ModelsAnalyzeResultsDocumentElementsCurrencyFieldType right) => left.Equals(right);
        /// <summary> Determines if two <see cref="ModelsAnalyzeResultsDocumentElementsCurrencyFieldType"/> values are not the same. </summary>
        public static bool operator !=(ModelsAnalyzeResultsDocumentElementsCurrencyFieldType left, ModelsAnalyzeResultsDocumentElementsCurrencyFieldType right) => !left.Equals(right);
        /// <summary> Converts a string to a <see cref="ModelsAnalyzeResultsDocumentElementsCurrencyFieldType"/>. </summary>
        public static implicit operator ModelsAnalyzeResultsDocumentElementsCurrencyFieldType(string value) => new ModelsAnalyzeResultsDocumentElementsCurrencyFieldType(value);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object obj) => obj is ModelsAnalyzeResultsDocumentElementsCurrencyFieldType other && Equals(other);
        /// <inheritdoc />
        public bool Equals(ModelsAnalyzeResultsDocumentElementsCurrencyFieldType other) => string.Equals(_value, other._value, StringComparison.InvariantCultureIgnoreCase);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;
        /// <inheritdoc />
        public override string ToString() => _value;
    }
}
