// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;
using System.Text.Json;
using Azure.Core;

namespace FormRecognizerClient.Models
{
    public partial class ModelsAnalyzeResultsDocumentElementsTable
    {
        internal static ModelsAnalyzeResultsDocumentElementsTable DeserializeModelsAnalyzeResultsDocumentElementsTable(JsonElement element)
        {
            int rowCount = default;
            int columnCount = default;
            IReadOnlyList<ModelsAnalyzeResultsDocumentElementsTableCell> cells = default;
            Optional<IReadOnlyList<ModelsAnalyzeResultsDocumentElementsBoundingRegion>> boundingRegions = default;
            IReadOnlyList<ModelsAnalyzeResultsDocumentElementsSpan> spans = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("rowCount"))
                {
                    rowCount = property.Value.GetInt32();
                    continue;
                }
                if (property.NameEquals("columnCount"))
                {
                    columnCount = property.Value.GetInt32();
                    continue;
                }
                if (property.NameEquals("cells"))
                {
                    List<ModelsAnalyzeResultsDocumentElementsTableCell> array = new List<ModelsAnalyzeResultsDocumentElementsTableCell>();
                    foreach (var item in property.Value.EnumerateArray())
                    {
                        array.Add(ModelsAnalyzeResultsDocumentElementsTableCell.DeserializeModelsAnalyzeResultsDocumentElementsTableCell(item));
                    }
                    cells = array;
                    continue;
                }
                if (property.NameEquals("boundingRegions"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    List<ModelsAnalyzeResultsDocumentElementsBoundingRegion> array = new List<ModelsAnalyzeResultsDocumentElementsBoundingRegion>();
                    foreach (var item in property.Value.EnumerateArray())
                    {
                        array.Add(ModelsAnalyzeResultsDocumentElementsBoundingRegion.DeserializeModelsAnalyzeResultsDocumentElementsBoundingRegion(item));
                    }
                    boundingRegions = array;
                    continue;
                }
                if (property.NameEquals("spans"))
                {
                    List<ModelsAnalyzeResultsDocumentElementsSpan> array = new List<ModelsAnalyzeResultsDocumentElementsSpan>();
                    foreach (var item in property.Value.EnumerateArray())
                    {
                        array.Add(ModelsAnalyzeResultsDocumentElementsSpan.DeserializeModelsAnalyzeResultsDocumentElementsSpan(item));
                    }
                    spans = array;
                    continue;
                }
            }
            return new ModelsAnalyzeResultsDocumentElementsTable(rowCount, columnCount, cells, Optional.ToList(boundingRegions), spans);
        }
    }
}
