// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.ComponentModel;

namespace FormRecognizerClient.Models
{
    /// <summary> The ModelsAnalyzeResultsDocumentElementsSignatureFieldValueSignature. </summary>
    internal readonly partial struct ModelsAnalyzeResultsDocumentElementsSignatureFieldValueSignature : IEquatable<ModelsAnalyzeResultsDocumentElementsSignatureFieldValueSignature>
    {
        private readonly string _value;

        /// <summary> Initializes a new instance of <see cref="ModelsAnalyzeResultsDocumentElementsSignatureFieldValueSignature"/>. </summary>
        /// <exception cref="ArgumentNullException"> <paramref name="value"/> is null. </exception>
        public ModelsAnalyzeResultsDocumentElementsSignatureFieldValueSignature(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        private const string SignedValue = "signed";
        private const string UnsignedValue = "unsigned";

        /// <summary> signed. </summary>
        public static ModelsAnalyzeResultsDocumentElementsSignatureFieldValueSignature Signed { get; } = new ModelsAnalyzeResultsDocumentElementsSignatureFieldValueSignature(SignedValue);
        /// <summary> unsigned. </summary>
        public static ModelsAnalyzeResultsDocumentElementsSignatureFieldValueSignature Unsigned { get; } = new ModelsAnalyzeResultsDocumentElementsSignatureFieldValueSignature(UnsignedValue);
        /// <summary> Determines if two <see cref="ModelsAnalyzeResultsDocumentElementsSignatureFieldValueSignature"/> values are the same. </summary>
        public static bool operator ==(ModelsAnalyzeResultsDocumentElementsSignatureFieldValueSignature left, ModelsAnalyzeResultsDocumentElementsSignatureFieldValueSignature right) => left.Equals(right);
        /// <summary> Determines if two <see cref="ModelsAnalyzeResultsDocumentElementsSignatureFieldValueSignature"/> values are not the same. </summary>
        public static bool operator !=(ModelsAnalyzeResultsDocumentElementsSignatureFieldValueSignature left, ModelsAnalyzeResultsDocumentElementsSignatureFieldValueSignature right) => !left.Equals(right);
        /// <summary> Converts a string to a <see cref="ModelsAnalyzeResultsDocumentElementsSignatureFieldValueSignature"/>. </summary>
        public static implicit operator ModelsAnalyzeResultsDocumentElementsSignatureFieldValueSignature(string value) => new ModelsAnalyzeResultsDocumentElementsSignatureFieldValueSignature(value);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object obj) => obj is ModelsAnalyzeResultsDocumentElementsSignatureFieldValueSignature other && Equals(other);
        /// <inheritdoc />
        public bool Equals(ModelsAnalyzeResultsDocumentElementsSignatureFieldValueSignature other) => string.Equals(_value, other._value, StringComparison.InvariantCultureIgnoreCase);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;
        /// <inheritdoc />
        public override string ToString() => _value;
    }
}
