// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using Azure.Core;

namespace FormRecognizerClient.Models
{
    /// <summary> The ModelsAnalyzeResultsDocumentElementsWord. </summary>
    public partial class ModelsAnalyzeResultsDocumentElementsWord
    {
        /// <summary> Initializes a new instance of ModelsAnalyzeResultsDocumentElementsWord. </summary>
        /// <param name="content"></param>
        /// <param name="span"></param>
        /// <param name="confidence"></param>
        /// <exception cref="ArgumentNullException"> <paramref name="content"/> or <paramref name="span"/> is null. </exception>
        internal ModelsAnalyzeResultsDocumentElementsWord(string content, ModelsAnalyzeResultsDocumentElementsSpan span, double confidence)
        {
            if (content == null)
            {
                throw new ArgumentNullException(nameof(content));
            }
            if (span == null)
            {
                throw new ArgumentNullException(nameof(span));
            }

            Content = content;
            Span = span;
            BoundingBox = new ChangeTrackingList<double>();
            Confidence = confidence;
        }

        /// <summary> Initializes a new instance of ModelsAnalyzeResultsDocumentElementsWord. </summary>
        /// <param name="content"></param>
        /// <param name="span"></param>
        /// <param name="boundingBox"></param>
        /// <param name="confidence"></param>
        internal ModelsAnalyzeResultsDocumentElementsWord(string content, ModelsAnalyzeResultsDocumentElementsSpan span, IReadOnlyList<double> boundingBox, double confidence)
        {
            Content = content;
            Span = span;
            BoundingBox = boundingBox;
            Confidence = confidence;
        }

        /// <summary> Gets the content. </summary>
        public string Content { get; }
        /// <summary> Gets the span. </summary>
        public ModelsAnalyzeResultsDocumentElementsSpan Span { get; }
        /// <summary> Gets the bounding box. </summary>
        public IReadOnlyList<double> BoundingBox { get; }
        /// <summary> Gets the confidence. </summary>
        public double Confidence { get; }
    }
}
