// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;
using System.Text.Json;
using Azure.Core;

namespace FormRecognizerClient.Models
{
    public partial class ModelsAnalyzeResultsDocumentElementsEntity
    {
        internal static ModelsAnalyzeResultsDocumentElementsEntity DeserializeModelsAnalyzeResultsDocumentElementsEntity(JsonElement element)
        {
            string category = default;
            Optional<string> subCategory = default;
            string content = default;
            Optional<IReadOnlyList<ModelsAnalyzeResultsDocumentElementsBoundingRegion>> boundingRegions = default;
            IReadOnlyList<ModelsAnalyzeResultsDocumentElementsSpan> spans = default;
            double confidence = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("category"))
                {
                    category = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("subCategory"))
                {
                    subCategory = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("content"))
                {
                    content = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("boundingRegions"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    List<ModelsAnalyzeResultsDocumentElementsBoundingRegion> array = new List<ModelsAnalyzeResultsDocumentElementsBoundingRegion>();
                    foreach (var item in property.Value.EnumerateArray())
                    {
                        array.Add(ModelsAnalyzeResultsDocumentElementsBoundingRegion.DeserializeModelsAnalyzeResultsDocumentElementsBoundingRegion(item));
                    }
                    boundingRegions = array;
                    continue;
                }
                if (property.NameEquals("spans"))
                {
                    List<ModelsAnalyzeResultsDocumentElementsSpan> array = new List<ModelsAnalyzeResultsDocumentElementsSpan>();
                    foreach (var item in property.Value.EnumerateArray())
                    {
                        array.Add(ModelsAnalyzeResultsDocumentElementsSpan.DeserializeModelsAnalyzeResultsDocumentElementsSpan(item));
                    }
                    spans = array;
                    continue;
                }
                if (property.NameEquals("confidence"))
                {
                    confidence = property.Value.GetDouble();
                    continue;
                }
            }
            return new ModelsAnalyzeResultsDocumentElementsEntity(category, subCategory.Value, content, Optional.ToList(boundingRegions), spans, confidence);
        }
    }
}
