// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.ComponentModel;

namespace FormRecognizerClient.Models
{
    /// <summary> The ModelsAnalyzeResultsDocumentElementsTimeFieldType. </summary>
    internal readonly partial struct ModelsAnalyzeResultsDocumentElementsTimeFieldType : IEquatable<ModelsAnalyzeResultsDocumentElementsTimeFieldType>
    {
        private readonly string _value;

        /// <summary> Initializes a new instance of <see cref="ModelsAnalyzeResultsDocumentElementsTimeFieldType"/>. </summary>
        /// <exception cref="ArgumentNullException"> <paramref name="value"/> is null. </exception>
        public ModelsAnalyzeResultsDocumentElementsTimeFieldType(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        private const string TimeValue = "time";

        /// <summary> time. </summary>
        public static ModelsAnalyzeResultsDocumentElementsTimeFieldType Time { get; } = new ModelsAnalyzeResultsDocumentElementsTimeFieldType(TimeValue);
        /// <summary> Determines if two <see cref="ModelsAnalyzeResultsDocumentElementsTimeFieldType"/> values are the same. </summary>
        public static bool operator ==(ModelsAnalyzeResultsDocumentElementsTimeFieldType left, ModelsAnalyzeResultsDocumentElementsTimeFieldType right) => left.Equals(right);
        /// <summary> Determines if two <see cref="ModelsAnalyzeResultsDocumentElementsTimeFieldType"/> values are not the same. </summary>
        public static bool operator !=(ModelsAnalyzeResultsDocumentElementsTimeFieldType left, ModelsAnalyzeResultsDocumentElementsTimeFieldType right) => !left.Equals(right);
        /// <summary> Converts a string to a <see cref="ModelsAnalyzeResultsDocumentElementsTimeFieldType"/>. </summary>
        public static implicit operator ModelsAnalyzeResultsDocumentElementsTimeFieldType(string value) => new ModelsAnalyzeResultsDocumentElementsTimeFieldType(value);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object obj) => obj is ModelsAnalyzeResultsDocumentElementsTimeFieldType other && Equals(other);
        /// <inheritdoc />
        public bool Equals(ModelsAnalyzeResultsDocumentElementsTimeFieldType other) => string.Equals(_value, other._value, StringComparison.InvariantCultureIgnoreCase);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;
        /// <inheritdoc />
        public override string ToString() => _value;
    }
}
