// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.ComponentModel;

namespace FormRecognizerClient.Models
{
    /// <summary> The ModelsAnalyzeResultsDocumentElementsDateFieldType. </summary>
    internal readonly partial struct ModelsAnalyzeResultsDocumentElementsDateFieldType : IEquatable<ModelsAnalyzeResultsDocumentElementsDateFieldType>
    {
        private readonly string _value;

        /// <summary> Initializes a new instance of <see cref="ModelsAnalyzeResultsDocumentElementsDateFieldType"/>. </summary>
        /// <exception cref="ArgumentNullException"> <paramref name="value"/> is null. </exception>
        public ModelsAnalyzeResultsDocumentElementsDateFieldType(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        private const string DateValue = "date";

        /// <summary> date. </summary>
        public static ModelsAnalyzeResultsDocumentElementsDateFieldType Date { get; } = new ModelsAnalyzeResultsDocumentElementsDateFieldType(DateValue);
        /// <summary> Determines if two <see cref="ModelsAnalyzeResultsDocumentElementsDateFieldType"/> values are the same. </summary>
        public static bool operator ==(ModelsAnalyzeResultsDocumentElementsDateFieldType left, ModelsAnalyzeResultsDocumentElementsDateFieldType right) => left.Equals(right);
        /// <summary> Determines if two <see cref="ModelsAnalyzeResultsDocumentElementsDateFieldType"/> values are not the same. </summary>
        public static bool operator !=(ModelsAnalyzeResultsDocumentElementsDateFieldType left, ModelsAnalyzeResultsDocumentElementsDateFieldType right) => !left.Equals(right);
        /// <summary> Converts a string to a <see cref="ModelsAnalyzeResultsDocumentElementsDateFieldType"/>. </summary>
        public static implicit operator ModelsAnalyzeResultsDocumentElementsDateFieldType(string value) => new ModelsAnalyzeResultsDocumentElementsDateFieldType(value);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object obj) => obj is ModelsAnalyzeResultsDocumentElementsDateFieldType other && Equals(other);
        /// <inheritdoc />
        public bool Equals(ModelsAnalyzeResultsDocumentElementsDateFieldType other) => string.Equals(_value, other._value, StringComparison.InvariantCultureIgnoreCase);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;
        /// <inheritdoc />
        public override string ToString() => _value;
    }
}
