// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace FormRecognizerClient.Models
{
    /// <summary> The ModelsAnalyzeResultsDocumentElementsSpan. </summary>
    public partial class ModelsAnalyzeResultsDocumentElementsSpan
    {
        /// <summary> Initializes a new instance of ModelsAnalyzeResultsDocumentElementsSpan. </summary>
        /// <param name="offset"></param>
        /// <param name="length"></param>
        internal ModelsAnalyzeResultsDocumentElementsSpan(int offset, int length)
        {
            Offset = offset;
            Length = length;
        }

        /// <summary> Gets the offset. </summary>
        public int Offset { get; }
        /// <summary> Gets the length. </summary>
        public int Length { get; }
    }
}
