// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Text.Json;
using Azure.Core;

namespace FormRecognizerClient.Models
{
    public partial class ModelsAnalyzeResultsAnalyzeOperation
    {
        internal static ModelsAnalyzeResultsAnalyzeOperation DeserializeModelsAnalyzeResultsAnalyzeOperation(JsonElement element)
        {
            ModelsAnalyzeResultsAnalyzeOperationStatus status = default;
            DateTimeOffset createdDateTime = default;
            DateTimeOffset lastUpdatedDateTime = default;
            Optional<Error> error = default;
            Optional<ModelsAnalyzeResultsAnalyzeResult> analyzeResult = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("status"))
                {
                    status = new ModelsAnalyzeResultsAnalyzeOperationStatus(property.Value.GetString());
                    continue;
                }
                if (property.NameEquals("createdDateTime"))
                {
                    createdDateTime = property.Value.GetDateTimeOffset("O");
                    continue;
                }
                if (property.NameEquals("lastUpdatedDateTime"))
                {
                    lastUpdatedDateTime = property.Value.GetDateTimeOffset("O");
                    continue;
                }
                if (property.NameEquals("error"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    error = Error.DeserializeError(property.Value);
                    continue;
                }
                if (property.NameEquals("analyzeResult"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    analyzeResult = ModelsAnalyzeResultsAnalyzeResult.DeserializeModelsAnalyzeResultsAnalyzeResult(property.Value);
                    continue;
                }
            }
            return new ModelsAnalyzeResultsAnalyzeOperation(status, createdDateTime, lastUpdatedDateTime, error.Value, analyzeResult.Value);
        }
    }
}
