// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace FormRecognizerClient.Models
{
    public partial class ModelsAnalyzeResultsDocumentElementsKeyValuePair
    {
        internal static ModelsAnalyzeResultsDocumentElementsKeyValuePair DeserializeModelsAnalyzeResultsDocumentElementsKeyValuePair(JsonElement element)
        {
            ModelsAnalyzeResultsDocumentElementsKeyValueElement key = default;
            Optional<ModelsAnalyzeResultsDocumentElementsKeyValueElement> value = default;
            double confidence = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("key"))
                {
                    key = ModelsAnalyzeResultsDocumentElementsKeyValueElement.DeserializeModelsAnalyzeResultsDocumentElementsKeyValueElement(property.Value);
                    continue;
                }
                if (property.NameEquals("value"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    value = ModelsAnalyzeResultsDocumentElementsKeyValueElement.DeserializeModelsAnalyzeResultsDocumentElementsKeyValueElement(property.Value);
                    continue;
                }
                if (property.NameEquals("confidence"))
                {
                    confidence = property.Value.GetDouble();
                    continue;
                }
            }
            return new ModelsAnalyzeResultsDocumentElementsKeyValuePair(key, value.Value, confidence);
        }
    }
}
