// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace FormRecognizerClient.Models
{
    /// <summary> The ModelsAnalyzeRequest. </summary>
    public partial class ModelsAnalyzeRequest
    {
        /// <summary> Initializes a new instance of ModelsAnalyzeRequest. </summary>
        public ModelsAnalyzeRequest()
        {
        }

        /// <summary> Gets or sets the url source. </summary>
        public string UrlSource { get; set; }
        /// <summary> Gets or sets the base 64 content source. </summary>
        public string Base64ContentSource { get; set; }
    }
}
