// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace FormRecognizerClient.Models
{
    /// <summary> The ModelsAnalyzeResultsDocumentElementsArrayFieldValueArrayItem. </summary>
    internal partial class ModelsAnalyzeResultsDocumentElementsArrayFieldValueArrayItem
    {
        /// <summary> Initializes a new instance of ModelsAnalyzeResultsDocumentElementsArrayFieldValueArrayItem. </summary>
        internal ModelsAnalyzeResultsDocumentElementsArrayFieldValueArrayItem()
        {
        }
    }
}
