// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.ComponentModel;

namespace FormRecognizerClient.Models
{
    /// <summary> The ModelsAnalyzeResultsDocumentElementsSelectionMarkFieldValueSelectionMark. </summary>
    internal readonly partial struct ModelsAnalyzeResultsDocumentElementsSelectionMarkFieldValueSelectionMark : IEquatable<ModelsAnalyzeResultsDocumentElementsSelectionMarkFieldValueSelectionMark>
    {
        private readonly string _value;

        /// <summary> Initializes a new instance of <see cref="ModelsAnalyzeResultsDocumentElementsSelectionMarkFieldValueSelectionMark"/>. </summary>
        /// <exception cref="ArgumentNullException"> <paramref name="value"/> is null. </exception>
        public ModelsAnalyzeResultsDocumentElementsSelectionMarkFieldValueSelectionMark(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        private const string SelectedValue = "selected";
        private const string UnselectedValue = "unselected";

        /// <summary> selected. </summary>
        public static ModelsAnalyzeResultsDocumentElementsSelectionMarkFieldValueSelectionMark Selected { get; } = new ModelsAnalyzeResultsDocumentElementsSelectionMarkFieldValueSelectionMark(SelectedValue);
        /// <summary> unselected. </summary>
        public static ModelsAnalyzeResultsDocumentElementsSelectionMarkFieldValueSelectionMark Unselected { get; } = new ModelsAnalyzeResultsDocumentElementsSelectionMarkFieldValueSelectionMark(UnselectedValue);
        /// <summary> Determines if two <see cref="ModelsAnalyzeResultsDocumentElementsSelectionMarkFieldValueSelectionMark"/> values are the same. </summary>
        public static bool operator ==(ModelsAnalyzeResultsDocumentElementsSelectionMarkFieldValueSelectionMark left, ModelsAnalyzeResultsDocumentElementsSelectionMarkFieldValueSelectionMark right) => left.Equals(right);
        /// <summary> Determines if two <see cref="ModelsAnalyzeResultsDocumentElementsSelectionMarkFieldValueSelectionMark"/> values are not the same. </summary>
        public static bool operator !=(ModelsAnalyzeResultsDocumentElementsSelectionMarkFieldValueSelectionMark left, ModelsAnalyzeResultsDocumentElementsSelectionMarkFieldValueSelectionMark right) => !left.Equals(right);
        /// <summary> Converts a string to a <see cref="ModelsAnalyzeResultsDocumentElementsSelectionMarkFieldValueSelectionMark"/>. </summary>
        public static implicit operator ModelsAnalyzeResultsDocumentElementsSelectionMarkFieldValueSelectionMark(string value) => new ModelsAnalyzeResultsDocumentElementsSelectionMarkFieldValueSelectionMark(value);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object obj) => obj is ModelsAnalyzeResultsDocumentElementsSelectionMarkFieldValueSelectionMark other && Equals(other);
        /// <inheritdoc />
        public bool Equals(ModelsAnalyzeResultsDocumentElementsSelectionMarkFieldValueSelectionMark other) => string.Equals(_value, other._value, StringComparison.InvariantCultureIgnoreCase);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;
        /// <inheritdoc />
        public override string ToString() => _value;
    }
}
