// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;
using Azure.Core;

namespace FormRecognizerClient.Models
{
    /// <summary> The ModelsDocumentFieldSchema. </summary>
    public partial class ModelsDocumentFieldSchema
    {
        /// <summary> Initializes a new instance of ModelsDocumentFieldSchema. </summary>
        /// <param name="type"></param>
        internal ModelsDocumentFieldSchema(ModelsDocumentFieldType type)
        {
            Type = type;
            Properties = new ChangeTrackingDictionary<string, ModelsDocumentFieldSchema>();
        }

        /// <summary> Initializes a new instance of ModelsDocumentFieldSchema. </summary>
        /// <param name="type"></param>
        /// <param name="description"></param>
        /// <param name="example"></param>
        /// <param name="items"></param>
        /// <param name="properties"> Dictionary of &lt;Models.DocumentFieldSchema&gt;. </param>
        internal ModelsDocumentFieldSchema(ModelsDocumentFieldType type, string description, string example, ModelsDocumentFieldSchema items, IReadOnlyDictionary<string, ModelsDocumentFieldSchema> properties)
        {
            Type = type;
            Description = description;
            Example = example;
            Items = items;
            Properties = properties;
        }

        /// <summary> Gets the type. </summary>
        public ModelsDocumentFieldType Type { get; }
        /// <summary> Gets the description. </summary>
        public string Description { get; }
        /// <summary> Gets the example. </summary>
        public string Example { get; }
        /// <summary> Gets the items. </summary>
        public ModelsDocumentFieldSchema Items { get; }
        /// <summary> Dictionary of &lt;Models.DocumentFieldSchema&gt;. </summary>
        public IReadOnlyDictionary<string, ModelsDocumentFieldSchema> Properties { get; }
    }
}
