// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.ComponentModel;

namespace FormRecognizerClient.Models
{
    /// <summary> The ModelsAnalyzeResultsDocumentElementsArrayFieldType. </summary>
    internal readonly partial struct ModelsAnalyzeResultsDocumentElementsArrayFieldType : IEquatable<ModelsAnalyzeResultsDocumentElementsArrayFieldType>
    {
        private readonly string _value;

        /// <summary> Initializes a new instance of <see cref="ModelsAnalyzeResultsDocumentElementsArrayFieldType"/>. </summary>
        /// <exception cref="ArgumentNullException"> <paramref name="value"/> is null. </exception>
        public ModelsAnalyzeResultsDocumentElementsArrayFieldType(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        private const string ArrayValue = "array";

        /// <summary> array. </summary>
        public static ModelsAnalyzeResultsDocumentElementsArrayFieldType Array { get; } = new ModelsAnalyzeResultsDocumentElementsArrayFieldType(ArrayValue);
        /// <summary> Determines if two <see cref="ModelsAnalyzeResultsDocumentElementsArrayFieldType"/> values are the same. </summary>
        public static bool operator ==(ModelsAnalyzeResultsDocumentElementsArrayFieldType left, ModelsAnalyzeResultsDocumentElementsArrayFieldType right) => left.Equals(right);
        /// <summary> Determines if two <see cref="ModelsAnalyzeResultsDocumentElementsArrayFieldType"/> values are not the same. </summary>
        public static bool operator !=(ModelsAnalyzeResultsDocumentElementsArrayFieldType left, ModelsAnalyzeResultsDocumentElementsArrayFieldType right) => !left.Equals(right);
        /// <summary> Converts a string to a <see cref="ModelsAnalyzeResultsDocumentElementsArrayFieldType"/>. </summary>
        public static implicit operator ModelsAnalyzeResultsDocumentElementsArrayFieldType(string value) => new ModelsAnalyzeResultsDocumentElementsArrayFieldType(value);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object obj) => obj is ModelsAnalyzeResultsDocumentElementsArrayFieldType other && Equals(other);
        /// <inheritdoc />
        public bool Equals(ModelsAnalyzeResultsDocumentElementsArrayFieldType other) => string.Equals(_value, other._value, StringComparison.InvariantCultureIgnoreCase);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;
        /// <inheritdoc />
        public override string ToString() => _value;
    }
}
