// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using System.Linq;
using Azure.Core;

namespace FormRecognizerClient.Models
{
    /// <summary> The ModelsAnalyzeResultsDocumentElementsEntity. </summary>
    public partial class ModelsAnalyzeResultsDocumentElementsEntity
    {
        /// <summary> Initializes a new instance of ModelsAnalyzeResultsDocumentElementsEntity. </summary>
        /// <param name="category"></param>
        /// <param name="content"></param>
        /// <param name="spans"></param>
        /// <param name="confidence"></param>
        /// <exception cref="ArgumentNullException"> <paramref name="category"/>, <paramref name="content"/> or <paramref name="spans"/> is null. </exception>
        internal ModelsAnalyzeResultsDocumentElementsEntity(string category, string content, IEnumerable<ModelsAnalyzeResultsDocumentElementsSpan> spans, double confidence)
        {
            if (category == null)
            {
                throw new ArgumentNullException(nameof(category));
            }
            if (content == null)
            {
                throw new ArgumentNullException(nameof(content));
            }
            if (spans == null)
            {
                throw new ArgumentNullException(nameof(spans));
            }

            Category = category;
            Content = content;
            BoundingRegions = new ChangeTrackingList<ModelsAnalyzeResultsDocumentElementsBoundingRegion>();
            Spans = spans.ToList();
            Confidence = confidence;
        }

        /// <summary> Initializes a new instance of ModelsAnalyzeResultsDocumentElementsEntity. </summary>
        /// <param name="category"></param>
        /// <param name="subCategory"></param>
        /// <param name="content"></param>
        /// <param name="boundingRegions"></param>
        /// <param name="spans"></param>
        /// <param name="confidence"></param>
        internal ModelsAnalyzeResultsDocumentElementsEntity(string category, string subCategory, string content, IReadOnlyList<ModelsAnalyzeResultsDocumentElementsBoundingRegion> boundingRegions, IReadOnlyList<ModelsAnalyzeResultsDocumentElementsSpan> spans, double confidence)
        {
            Category = category;
            SubCategory = subCategory;
            Content = content;
            BoundingRegions = boundingRegions;
            Spans = spans;
            Confidence = confidence;
        }

        /// <summary> Gets the category. </summary>
        public string Category { get; }
        /// <summary> Gets the sub category. </summary>
        public string SubCategory { get; }
        /// <summary> Gets the content. </summary>
        public string Content { get; }
        /// <summary> Gets the bounding regions. </summary>
        public IReadOnlyList<ModelsAnalyzeResultsDocumentElementsBoundingRegion> BoundingRegions { get; }
        /// <summary> Gets the spans. </summary>
        public IReadOnlyList<ModelsAnalyzeResultsDocumentElementsSpan> Spans { get; }
        /// <summary> Gets the confidence. </summary>
        public double Confidence { get; }
    }
}
