// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace FormRecognizerClient.Models
{
    /// <summary> The ModelsAnalyzeResultsAnalyzeOperation. </summary>
    public partial class ModelsAnalyzeResultsAnalyzeOperation
    {
        /// <summary> Initializes a new instance of ModelsAnalyzeResultsAnalyzeOperation. </summary>
        /// <param name="status"></param>
        /// <param name="createdDateTime"></param>
        /// <param name="lastUpdatedDateTime"></param>
        internal ModelsAnalyzeResultsAnalyzeOperation(ModelsAnalyzeResultsAnalyzeOperationStatus status, DateTimeOffset createdDateTime, DateTimeOffset lastUpdatedDateTime)
        {
            Status = status;
            CreatedDateTime = createdDateTime;
            LastUpdatedDateTime = lastUpdatedDateTime;
        }

        /// <summary> Initializes a new instance of ModelsAnalyzeResultsAnalyzeOperation. </summary>
        /// <param name="status"></param>
        /// <param name="createdDateTime"></param>
        /// <param name="lastUpdatedDateTime"></param>
        /// <param name="error"></param>
        /// <param name="analyzeResult"></param>
        internal ModelsAnalyzeResultsAnalyzeOperation(ModelsAnalyzeResultsAnalyzeOperationStatus status, DateTimeOffset createdDateTime, DateTimeOffset lastUpdatedDateTime, Error error, ModelsAnalyzeResultsAnalyzeResult analyzeResult)
        {
            Status = status;
            CreatedDateTime = createdDateTime;
            LastUpdatedDateTime = lastUpdatedDateTime;
            Error = error;
            AnalyzeResult = analyzeResult;
        }

        /// <summary> Gets the status. </summary>
        public ModelsAnalyzeResultsAnalyzeOperationStatus Status { get; }
        /// <summary> Gets the created date time. </summary>
        public DateTimeOffset CreatedDateTime { get; }
        /// <summary> Gets the last updated date time. </summary>
        public DateTimeOffset LastUpdatedDateTime { get; }
        /// <summary> Gets the error. </summary>
        public Error Error { get; }
        /// <summary> Gets the analyze result. </summary>
        public ModelsAnalyzeResultsAnalyzeResult AnalyzeResult { get; }
    }
}
