// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;
using System.Text.Json;
using Azure.Core;

namespace FormRecognizerClient.Models
{
    public partial class ModelsAnalyzeResultsDocumentElementsWord
    {
        internal static ModelsAnalyzeResultsDocumentElementsWord DeserializeModelsAnalyzeResultsDocumentElementsWord(JsonElement element)
        {
            string content = default;
            ModelsAnalyzeResultsDocumentElementsSpan span = default;
            Optional<IReadOnlyList<double>> boundingBox = default;
            double confidence = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("content"))
                {
                    content = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("span"))
                {
                    span = ModelsAnalyzeResultsDocumentElementsSpan.DeserializeModelsAnalyzeResultsDocumentElementsSpan(property.Value);
                    continue;
                }
                if (property.NameEquals("boundingBox"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    List<double> array = new List<double>();
                    foreach (var item in property.Value.EnumerateArray())
                    {
                        array.Add(item.GetDouble());
                    }
                    boundingBox = array;
                    continue;
                }
                if (property.NameEquals("confidence"))
                {
                    confidence = property.Value.GetDouble();
                    continue;
                }
            }
            return new ModelsAnalyzeResultsDocumentElementsWord(content, span, Optional.ToList(boundingBox), confidence);
        }
    }
}
