// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.ComponentModel;

namespace FormRecognizerClient.Models
{
    /// <summary> The ModelsAnalyzeResultsDocumentElementsObjectFieldType. </summary>
    internal readonly partial struct ModelsAnalyzeResultsDocumentElementsObjectFieldType : IEquatable<ModelsAnalyzeResultsDocumentElementsObjectFieldType>
    {
        private readonly string _value;

        /// <summary> Initializes a new instance of <see cref="ModelsAnalyzeResultsDocumentElementsObjectFieldType"/>. </summary>
        /// <exception cref="ArgumentNullException"> <paramref name="value"/> is null. </exception>
        public ModelsAnalyzeResultsDocumentElementsObjectFieldType(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        private const string ObjectValue = "object";

        /// <summary> object. </summary>
        public static ModelsAnalyzeResultsDocumentElementsObjectFieldType Object { get; } = new ModelsAnalyzeResultsDocumentElementsObjectFieldType(ObjectValue);
        /// <summary> Determines if two <see cref="ModelsAnalyzeResultsDocumentElementsObjectFieldType"/> values are the same. </summary>
        public static bool operator ==(ModelsAnalyzeResultsDocumentElementsObjectFieldType left, ModelsAnalyzeResultsDocumentElementsObjectFieldType right) => left.Equals(right);
        /// <summary> Determines if two <see cref="ModelsAnalyzeResultsDocumentElementsObjectFieldType"/> values are not the same. </summary>
        public static bool operator !=(ModelsAnalyzeResultsDocumentElementsObjectFieldType left, ModelsAnalyzeResultsDocumentElementsObjectFieldType right) => !left.Equals(right);
        /// <summary> Converts a string to a <see cref="ModelsAnalyzeResultsDocumentElementsObjectFieldType"/>. </summary>
        public static implicit operator ModelsAnalyzeResultsDocumentElementsObjectFieldType(string value) => new ModelsAnalyzeResultsDocumentElementsObjectFieldType(value);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object obj) => obj is ModelsAnalyzeResultsDocumentElementsObjectFieldType other && Equals(other);
        /// <inheritdoc />
        public bool Equals(ModelsAnalyzeResultsDocumentElementsObjectFieldType other) => string.Equals(_value, other._value, StringComparison.InvariantCultureIgnoreCase);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;
        /// <inheritdoc />
        public override string ToString() => _value;
    }
}
