// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using System.Linq;
using Azure.Core;

namespace FormRecognizerClient.Models
{
    /// <summary> The ModelsAnalyzeResultsDocumentElementsObjectField. </summary>
    internal partial class ModelsAnalyzeResultsDocumentElementsObjectField
    {
        /// <summary> Initializes a new instance of ModelsAnalyzeResultsDocumentElementsObjectField. </summary>
        /// <param name="type"></param>
        /// <param name="valueObject"> Dictionary of &lt;components·1mheujy·schemas·models-analyzeresults-documentelements-objectfield·properties·valueobject·additionalproperties&gt;. </param>
        /// <param name="content"></param>
        /// <param name="spans"></param>
        /// <param name="confidence"></param>
        /// <exception cref="ArgumentNullException"> <paramref name="valueObject"/>, <paramref name="content"/> or <paramref name="spans"/> is null. </exception>
        internal ModelsAnalyzeResultsDocumentElementsObjectField(ModelsAnalyzeResultsDocumentElementsObjectFieldType type, IReadOnlyDictionary<string, Components1MheujySchemasModelsAnalyzeresultsDocumentelementsObjectfieldPropertiesValueobjectAdditionalproperties> valueObject, string content, IEnumerable<ModelsAnalyzeResultsDocumentElementsSpan> spans, double confidence)
        {
            if (valueObject == null)
            {
                throw new ArgumentNullException(nameof(valueObject));
            }
            if (content == null)
            {
                throw new ArgumentNullException(nameof(content));
            }
            if (spans == null)
            {
                throw new ArgumentNullException(nameof(spans));
            }

            Type = type;
            ValueObject = valueObject;
            Content = content;
            BoundingRegions = new ChangeTrackingList<ModelsAnalyzeResultsDocumentElementsBoundingRegion>();
            Spans = spans.ToList();
            Confidence = confidence;
        }

        /// <summary> Gets the type. </summary>
        public ModelsAnalyzeResultsDocumentElementsObjectFieldType Type { get; }
        /// <summary> Dictionary of &lt;components·1mheujy·schemas·models-analyzeresults-documentelements-objectfield·properties·valueobject·additionalproperties&gt;. </summary>
        public IReadOnlyDictionary<string, Components1MheujySchemasModelsAnalyzeresultsDocumentelementsObjectfieldPropertiesValueobjectAdditionalproperties> ValueObject { get; }
        /// <summary> Gets the content. </summary>
        public string Content { get; }
        /// <summary> Gets the bounding regions. </summary>
        public IReadOnlyList<ModelsAnalyzeResultsDocumentElementsBoundingRegion> BoundingRegions { get; }
        /// <summary> Gets the spans. </summary>
        public IReadOnlyList<ModelsAnalyzeResultsDocumentElementsSpan> Spans { get; }
        /// <summary> Gets the confidence. </summary>
        public double Confidence { get; }
    }
}
