// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using Azure.Core;

namespace FormRecognizerClient.Models
{
    /// <summary> The ModelsModelSummary. </summary>
    public partial class ModelsModelSummary
    {
        /// <summary> Initializes a new instance of ModelsModelSummary. </summary>
        /// <param name="modelId"></param>
        /// <param name="createdDateTime"></param>
        /// <exception cref="ArgumentNullException"> <paramref name="modelId"/> is null. </exception>
        internal ModelsModelSummary(string modelId, DateTimeOffset createdDateTime)
        {
            if (modelId == null)
            {
                throw new ArgumentNullException(nameof(modelId));
            }

            ModelId = modelId;
            CreatedDateTime = createdDateTime;
            Tags = new ChangeTrackingDictionary<string, string>();
        }

        /// <summary> Initializes a new instance of ModelsModelSummary. </summary>
        /// <param name="modelId"></param>
        /// <param name="createdDateTime"></param>
        /// <param name="apiVersion"></param>
        /// <param name="tags"> Dictionary of &lt;string&gt;. </param>
        internal ModelsModelSummary(string modelId, DateTimeOffset createdDateTime, string apiVersion, IReadOnlyDictionary<string, string> tags)
        {
            ModelId = modelId;
            CreatedDateTime = createdDateTime;
            ApiVersion = apiVersion;
            Tags = tags;
        }

        /// <summary> Gets the model id. </summary>
        public string ModelId { get; }
        /// <summary> Gets the created date time. </summary>
        public DateTimeOffset CreatedDateTime { get; }
        /// <summary> Gets the api version. </summary>
        public string ApiVersion { get; }
        /// <summary> Dictionary of &lt;string&gt;. </summary>
        public IReadOnlyDictionary<string, string> Tags { get; }
    }
}
