// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace FormRecognizerClient.Models
{
    public partial class ModelsAnalyzeRequest : IUtf8JsonSerializable
    {
        void IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            if (Optional.IsDefined(UrlSource))
            {
                writer.WritePropertyName("urlSource");
                writer.WriteStringValue(UrlSource);
            }
            if (Optional.IsDefined(Base64ContentSource))
            {
                writer.WritePropertyName("base64ContentSource");
                writer.WriteStringValue(Base64ContentSource);
            }
            writer.WriteEndObject();
        }
    }
}
