// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;
using System.Text.Json;
using Azure.Core;

namespace FormRecognizerClient.Models
{
    public partial class ModelsAnalyzeResultsDocumentElementsBoundingRegion
    {
        internal static ModelsAnalyzeResultsDocumentElementsBoundingRegion DeserializeModelsAnalyzeResultsDocumentElementsBoundingRegion(JsonElement element)
        {
            int pageNumber = default;
            IReadOnlyList<double> boundingBox = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("pageNumber"))
                {
                    pageNumber = property.Value.GetInt32();
                    continue;
                }
                if (property.NameEquals("boundingBox"))
                {
                    List<double> array = new List<double>();
                    foreach (var item in property.Value.EnumerateArray())
                    {
                        array.Add(item.GetDouble());
                    }
                    boundingBox = array;
                    continue;
                }
            }
            return new ModelsAnalyzeResultsDocumentElementsBoundingRegion(pageNumber, boundingBox);
        }
    }
}
