// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace FormRecognizerClient.Models
{
    /// <summary> The ModelsAnalyzeResultsDocumentElementsKeyValuePair. </summary>
    public partial class ModelsAnalyzeResultsDocumentElementsKeyValuePair
    {
        /// <summary> Initializes a new instance of ModelsAnalyzeResultsDocumentElementsKeyValuePair. </summary>
        /// <param name="key"></param>
        /// <param name="confidence"></param>
        /// <exception cref="ArgumentNullException"> <paramref name="key"/> is null. </exception>
        internal ModelsAnalyzeResultsDocumentElementsKeyValuePair(ModelsAnalyzeResultsDocumentElementsKeyValueElement key, double confidence)
        {
            if (key == null)
            {
                throw new ArgumentNullException(nameof(key));
            }

            Key = key;
            Confidence = confidence;
        }

        /// <summary> Initializes a new instance of ModelsAnalyzeResultsDocumentElementsKeyValuePair. </summary>
        /// <param name="key"></param>
        /// <param name="value"></param>
        /// <param name="confidence"></param>
        internal ModelsAnalyzeResultsDocumentElementsKeyValuePair(ModelsAnalyzeResultsDocumentElementsKeyValueElement key, ModelsAnalyzeResultsDocumentElementsKeyValueElement value, double confidence)
        {
            Key = key;
            Value = value;
            Confidence = confidence;
        }

        /// <summary> Gets the key. </summary>
        public ModelsAnalyzeResultsDocumentElementsKeyValueElement Key { get; }
        /// <summary> Gets the value. </summary>
        public ModelsAnalyzeResultsDocumentElementsKeyValueElement Value { get; }
        /// <summary> Gets the confidence. </summary>
        public double Confidence { get; }
    }
}
