// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.ComponentModel;

namespace FormRecognizerClient.Models
{
    /// <summary> The ModelsAnalyzeResultsDocumentElementsPageUnit. </summary>
    public readonly partial struct ModelsAnalyzeResultsDocumentElementsPageUnit : IEquatable<ModelsAnalyzeResultsDocumentElementsPageUnit>
    {
        private readonly string _value;

        /// <summary> Initializes a new instance of <see cref="ModelsAnalyzeResultsDocumentElementsPageUnit"/>. </summary>
        /// <exception cref="ArgumentNullException"> <paramref name="value"/> is null. </exception>
        public ModelsAnalyzeResultsDocumentElementsPageUnit(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        private const string PixelValue = "pixel";
        private const string InchValue = "inch";

        /// <summary> pixel. </summary>
        public static ModelsAnalyzeResultsDocumentElementsPageUnit Pixel { get; } = new ModelsAnalyzeResultsDocumentElementsPageUnit(PixelValue);
        /// <summary> inch. </summary>
        public static ModelsAnalyzeResultsDocumentElementsPageUnit Inch { get; } = new ModelsAnalyzeResultsDocumentElementsPageUnit(InchValue);
        /// <summary> Determines if two <see cref="ModelsAnalyzeResultsDocumentElementsPageUnit"/> values are the same. </summary>
        public static bool operator ==(ModelsAnalyzeResultsDocumentElementsPageUnit left, ModelsAnalyzeResultsDocumentElementsPageUnit right) => left.Equals(right);
        /// <summary> Determines if two <see cref="ModelsAnalyzeResultsDocumentElementsPageUnit"/> values are not the same. </summary>
        public static bool operator !=(ModelsAnalyzeResultsDocumentElementsPageUnit left, ModelsAnalyzeResultsDocumentElementsPageUnit right) => !left.Equals(right);
        /// <summary> Converts a string to a <see cref="ModelsAnalyzeResultsDocumentElementsPageUnit"/>. </summary>
        public static implicit operator ModelsAnalyzeResultsDocumentElementsPageUnit(string value) => new ModelsAnalyzeResultsDocumentElementsPageUnit(value);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object obj) => obj is ModelsAnalyzeResultsDocumentElementsPageUnit other && Equals(other);
        /// <inheritdoc />
        public bool Equals(ModelsAnalyzeResultsDocumentElementsPageUnit other) => string.Equals(_value, other._value, StringComparison.InvariantCultureIgnoreCase);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;
        /// <inheritdoc />
        public override string ToString() => _value;
    }
}
