// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using System.Linq;
using Azure.Core;

namespace FormRecognizerClient.Models
{
    /// <summary> The ModelsAnalyzeResultsDocumentElementsLine. </summary>
    public partial class ModelsAnalyzeResultsDocumentElementsLine
    {
        /// <summary> Initializes a new instance of ModelsAnalyzeResultsDocumentElementsLine. </summary>
        /// <param name="content"></param>
        /// <param name="spans"></param>
        /// <exception cref="ArgumentNullException"> <paramref name="content"/> or <paramref name="spans"/> is null. </exception>
        internal ModelsAnalyzeResultsDocumentElementsLine(string content, IEnumerable<ModelsAnalyzeResultsDocumentElementsSpan> spans)
        {
            if (content == null)
            {
                throw new ArgumentNullException(nameof(content));
            }
            if (spans == null)
            {
                throw new ArgumentNullException(nameof(spans));
            }

            Content = content;
            BoundingBox = new ChangeTrackingList<double>();
            Spans = spans.ToList();
        }

        /// <summary> Initializes a new instance of ModelsAnalyzeResultsDocumentElementsLine. </summary>
        /// <param name="content"></param>
        /// <param name="boundingBox"></param>
        /// <param name="spans"></param>
        internal ModelsAnalyzeResultsDocumentElementsLine(string content, IReadOnlyList<double> boundingBox, IReadOnlyList<ModelsAnalyzeResultsDocumentElementsSpan> spans)
        {
            Content = content;
            BoundingBox = boundingBox;
            Spans = spans;
        }

        /// <summary> Gets the content. </summary>
        public string Content { get; }
        /// <summary> Gets the bounding box. </summary>
        public IReadOnlyList<double> BoundingBox { get; }
        /// <summary> Gets the spans. </summary>
        public IReadOnlyList<ModelsAnalyzeResultsDocumentElementsSpan> Spans { get; }
    }
}
