// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;

namespace FormRecognizerClient.Models
{
    /// <summary> The OperationsGetOperationResponse. </summary>
    public partial class OperationsGetOperationResponse : OperationsOperationInfo
    {
        /// <summary> Initializes a new instance of OperationsGetOperationResponse. </summary>
        /// <param name="operationId"></param>
        /// <param name="status"></param>
        /// <param name="createdDateTime"></param>
        /// <param name="lastUpdatedDateTime"></param>
        /// <param name="kind"></param>
        /// <param name="resourceLocation"></param>
        /// <exception cref="ArgumentNullException"> <paramref name="operationId"/> or <paramref name="resourceLocation"/> is null. </exception>
        internal OperationsGetOperationResponse(string operationId, OperationsOperationStatus status, DateTimeOffset createdDateTime, DateTimeOffset lastUpdatedDateTime, OperationsOperationKind kind, string resourceLocation) : base(operationId, status, createdDateTime, lastUpdatedDateTime, kind, resourceLocation)
        {
            if (operationId == null)
            {
                throw new ArgumentNullException(nameof(operationId));
            }
            if (resourceLocation == null)
            {
                throw new ArgumentNullException(nameof(resourceLocation));
            }
        }

        /// <summary> Initializes a new instance of OperationsGetOperationResponse. </summary>
        /// <param name="operationId"></param>
        /// <param name="status"></param>
        /// <param name="percentCompleted"></param>
        /// <param name="createdDateTime"></param>
        /// <param name="lastUpdatedDateTime"></param>
        /// <param name="kind"></param>
        /// <param name="resourceLocation"></param>
        /// <param name="apiVersion"></param>
        /// <param name="tags"> Dictionary of &lt;string&gt;. </param>
        /// <param name="error"></param>
        /// <param name="result"></param>
        internal OperationsGetOperationResponse(string operationId, OperationsOperationStatus status, int? percentCompleted, DateTimeOffset createdDateTime, DateTimeOffset lastUpdatedDateTime, OperationsOperationKind kind, string resourceLocation, string apiVersion, IReadOnlyDictionary<string, string> tags, Error error, ModelsModelInfo result) : base(operationId, status, percentCompleted, createdDateTime, lastUpdatedDateTime, kind, resourceLocation, apiVersion, tags)
        {
            Error = error;
            Result = result;
        }

        /// <summary> Gets the error. </summary>
        public Error Error { get; }
        /// <summary> Gets the result. </summary>
        public ModelsModelInfo Result { get; }
    }
}
