// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.ComponentModel;

namespace FormRecognizerClient.Models
{
    /// <summary> The OperationsOperationKind. </summary>
    public readonly partial struct OperationsOperationKind : IEquatable<OperationsOperationKind>
    {
        private readonly string _value;

        /// <summary> Initializes a new instance of <see cref="OperationsOperationKind"/>. </summary>
        /// <exception cref="ArgumentNullException"> <paramref name="value"/> is null. </exception>
        public OperationsOperationKind(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        private const string DocumentModelBuildValue = "documentModelBuild";
        private const string DocumentModelComposeValue = "documentModelCompose";
        private const string DocumentModelCopyToValue = "documentModelCopyTo";

        /// <summary> documentModelBuild. </summary>
        public static OperationsOperationKind DocumentModelBuild { get; } = new OperationsOperationKind(DocumentModelBuildValue);
        /// <summary> documentModelCompose. </summary>
        public static OperationsOperationKind DocumentModelCompose { get; } = new OperationsOperationKind(DocumentModelComposeValue);
        /// <summary> documentModelCopyTo. </summary>
        public static OperationsOperationKind DocumentModelCopyTo { get; } = new OperationsOperationKind(DocumentModelCopyToValue);
        /// <summary> Determines if two <see cref="OperationsOperationKind"/> values are the same. </summary>
        public static bool operator ==(OperationsOperationKind left, OperationsOperationKind right) => left.Equals(right);
        /// <summary> Determines if two <see cref="OperationsOperationKind"/> values are not the same. </summary>
        public static bool operator !=(OperationsOperationKind left, OperationsOperationKind right) => !left.Equals(right);
        /// <summary> Converts a string to a <see cref="OperationsOperationKind"/>. </summary>
        public static implicit operator OperationsOperationKind(string value) => new OperationsOperationKind(value);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object obj) => obj is OperationsOperationKind other && Equals(other);
        /// <inheritdoc />
        public bool Equals(OperationsOperationKind other) => string.Equals(_value, other._value, StringComparison.InvariantCultureIgnoreCase);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;
        /// <inheritdoc />
        public override string ToString() => _value;
    }
}
