// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.ComponentModel;

namespace FormRecognizerClient.Models
{
    /// <summary> The OperationsOperationStatus. </summary>
    public readonly partial struct OperationsOperationStatus : IEquatable<OperationsOperationStatus>
    {
        private readonly string _value;

        /// <summary> Initializes a new instance of <see cref="OperationsOperationStatus"/>. </summary>
        /// <exception cref="ArgumentNullException"> <paramref name="value"/> is null. </exception>
        public OperationsOperationStatus(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        private const string NotStartedValue = "notStarted";
        private const string RunningValue = "running";
        private const string FailedValue = "failed";
        private const string SucceededValue = "succeeded";
        private const string CanceledValue = "canceled";

        /// <summary> notStarted. </summary>
        public static OperationsOperationStatus NotStarted { get; } = new OperationsOperationStatus(NotStartedValue);
        /// <summary> running. </summary>
        public static OperationsOperationStatus Running { get; } = new OperationsOperationStatus(RunningValue);
        /// <summary> failed. </summary>
        public static OperationsOperationStatus Failed { get; } = new OperationsOperationStatus(FailedValue);
        /// <summary> succeeded. </summary>
        public static OperationsOperationStatus Succeeded { get; } = new OperationsOperationStatus(SucceededValue);
        /// <summary> canceled. </summary>
        public static OperationsOperationStatus Canceled { get; } = new OperationsOperationStatus(CanceledValue);
        /// <summary> Determines if two <see cref="OperationsOperationStatus"/> values are the same. </summary>
        public static bool operator ==(OperationsOperationStatus left, OperationsOperationStatus right) => left.Equals(right);
        /// <summary> Determines if two <see cref="OperationsOperationStatus"/> values are not the same. </summary>
        public static bool operator !=(OperationsOperationStatus left, OperationsOperationStatus right) => !left.Equals(right);
        /// <summary> Converts a string to a <see cref="OperationsOperationStatus"/>. </summary>
        public static implicit operator OperationsOperationStatus(string value) => new OperationsOperationStatus(value);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object obj) => obj is OperationsOperationStatus other && Equals(other);
        /// <inheritdoc />
        public bool Equals(OperationsOperationStatus other) => string.Equals(_value, other._value, StringComparison.InvariantCultureIgnoreCase);

        /// <inheritdoc />
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;
        /// <inheritdoc />
        public override string ToString() => _value;
    }
}
