// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using System.Linq;

namespace FormRecognizerClient.Models
{
    /// <summary> The PageModelsModelSummary. </summary>
    public partial class PageModelsModelSummary
    {
        /// <summary> Initializes a new instance of PageModelsModelSummary. </summary>
        /// <param name="value"></param>
        /// <exception cref="ArgumentNullException"> <paramref name="value"/> is null. </exception>
        internal PageModelsModelSummary(IEnumerable<ModelsModelSummary> value)
        {
            if (value == null)
            {
                throw new ArgumentNullException(nameof(value));
            }

            Value = value.ToList();
        }

        /// <summary> Initializes a new instance of PageModelsModelSummary. </summary>
        /// <param name="value"></param>
        /// <param name="nextLink"></param>
        internal PageModelsModelSummary(IReadOnlyList<ModelsModelSummary> value, string nextLink)
        {
            Value = value;
            NextLink = nextLink;
        }

        /// <summary> Gets the value. </summary>
        public IReadOnlyList<ModelsModelSummary> Value { get; }
        /// <summary> Gets the next link. </summary>
        public string NextLink { get; }
    }
}
