// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace FormRecognizerClient.Models
{
    public partial class ResourceInfo
    {
        internal static ResourceInfo DeserializeResourceInfo(JsonElement element)
        {
            CustomDocumentModelInfo customDocumentModels = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("customDocumentModels"))
                {
                    customDocumentModels = CustomDocumentModelInfo.DeserializeCustomDocumentModelInfo(property.Value);
                    continue;
                }
            }
            return new ResourceInfo(customDocumentModels);
        }
    }
}
