# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

try:
    from ._models_py3 import AzureBlobContentSource
    from ._models_py3 import BuildModelRequest
    from ._models_py3 import ComponentModelInfo
    from ._models_py3 import ComposeModelRequest
    from ._models_py3 import CopyAuthorization
    from ._models_py3 import CopyAuthorizationRequest
    from ._models_py3 import CustomDocumentModelInfo
    from ._models_py3 import Error
    from ._models_py3 import ModelsAnalyzeRequest
    from ._models_py3 import ModelsAnalyzeResultsAnalyzeOperation
    from ._models_py3 import ModelsAnalyzeResultsAnalyzeResult
    from ._models_py3 import ModelsAnalyzeResultsDocumentElementsArrayField
    from ._models_py3 import ModelsAnalyzeResultsDocumentElementsBoundingRegion
    from ._models_py3 import ModelsAnalyzeResultsDocumentElementsCountryRegionField
    from ._models_py3 import ModelsAnalyzeResultsDocumentElementsCurrencyField
    from ._models_py3 import ModelsAnalyzeResultsDocumentElementsCurrencyValue
    from ._models_py3 import ModelsAnalyzeResultsDocumentElementsDateField
    from ._models_py3 import ModelsAnalyzeResultsDocumentElementsDocument
    from ._models_py3 import ModelsAnalyzeResultsDocumentElementsEntity
    from ._models_py3 import ModelsAnalyzeResultsDocumentElementsIntegerField
    from ._models_py3 import ModelsAnalyzeResultsDocumentElementsKeyValueElement
    from ._models_py3 import ModelsAnalyzeResultsDocumentElementsKeyValuePair
    from ._models_py3 import ModelsAnalyzeResultsDocumentElementsLanguage
    from ._models_py3 import ModelsAnalyzeResultsDocumentElementsLine
    from ._models_py3 import ModelsAnalyzeResultsDocumentElementsObjectField
    from ._models_py3 import ModelsAnalyzeResultsDocumentElementsPage
    from ._models_py3 import ModelsAnalyzeResultsDocumentElementsPhoneNumberField
    from ._models_py3 import ModelsAnalyzeResultsDocumentElementsSelectionMark
    from ._models_py3 import ModelsAnalyzeResultsDocumentElementsSelectionMarkField
    from ._models_py3 import ModelsAnalyzeResultsDocumentElementsSignatureField
    from ._models_py3 import ModelsAnalyzeResultsDocumentElementsSpan
    from ._models_py3 import ModelsAnalyzeResultsDocumentElementsStringField
    from ._models_py3 import ModelsAnalyzeResultsDocumentElementsStyle
    from ._models_py3 import ModelsAnalyzeResultsDocumentElementsTable
    from ._models_py3 import ModelsAnalyzeResultsDocumentElementsTableCell
    from ._models_py3 import ModelsAnalyzeResultsDocumentElementsTimeField
    from ._models_py3 import ModelsAnalyzeResultsDocumentElementsWord
    from ._models_py3 import ModelsDocTypeInfo
    from ._models_py3 import ModelsDocumentFieldSchema
    from ._models_py3 import ModelsModelInfo
    from ._models_py3 import ModelsModelSummary
    from ._models_py3 import OperationsGetOperationResponse
    from ._models_py3 import OperationsOperationInfo
    from ._models_py3 import PageModelsModelSummary
    from ._models_py3 import PageOperationsOperationInfo
    from ._models_py3 import ResourceInfo
except (SyntaxError, ImportError):
    from ._models import AzureBlobContentSource  # type: ignore
    from ._models import BuildModelRequest  # type: ignore
    from ._models import ComponentModelInfo  # type: ignore
    from ._models import ComposeModelRequest  # type: ignore
    from ._models import CopyAuthorization  # type: ignore
    from ._models import CopyAuthorizationRequest  # type: ignore
    from ._models import CustomDocumentModelInfo  # type: ignore
    from ._models import Error  # type: ignore
    from ._models import ModelsAnalyzeRequest  # type: ignore
    from ._models import ModelsAnalyzeResultsAnalyzeOperation  # type: ignore
    from ._models import ModelsAnalyzeResultsAnalyzeResult  # type: ignore
    from ._models import ModelsAnalyzeResultsDocumentElementsArrayField  # type: ignore
    from ._models import ModelsAnalyzeResultsDocumentElementsBoundingRegion  # type: ignore
    from ._models import ModelsAnalyzeResultsDocumentElementsCountryRegionField  # type: ignore
    from ._models import ModelsAnalyzeResultsDocumentElementsCurrencyField  # type: ignore
    from ._models import ModelsAnalyzeResultsDocumentElementsCurrencyValue  # type: ignore
    from ._models import ModelsAnalyzeResultsDocumentElementsDateField  # type: ignore
    from ._models import ModelsAnalyzeResultsDocumentElementsDocument  # type: ignore
    from ._models import ModelsAnalyzeResultsDocumentElementsEntity  # type: ignore
    from ._models import ModelsAnalyzeResultsDocumentElementsIntegerField  # type: ignore
    from ._models import ModelsAnalyzeResultsDocumentElementsKeyValueElement  # type: ignore
    from ._models import ModelsAnalyzeResultsDocumentElementsKeyValuePair  # type: ignore
    from ._models import ModelsAnalyzeResultsDocumentElementsLanguage  # type: ignore
    from ._models import ModelsAnalyzeResultsDocumentElementsLine  # type: ignore
    from ._models import ModelsAnalyzeResultsDocumentElementsObjectField  # type: ignore
    from ._models import ModelsAnalyzeResultsDocumentElementsPage  # type: ignore
    from ._models import ModelsAnalyzeResultsDocumentElementsPhoneNumberField  # type: ignore
    from ._models import ModelsAnalyzeResultsDocumentElementsSelectionMark  # type: ignore
    from ._models import ModelsAnalyzeResultsDocumentElementsSelectionMarkField  # type: ignore
    from ._models import ModelsAnalyzeResultsDocumentElementsSignatureField  # type: ignore
    from ._models import ModelsAnalyzeResultsDocumentElementsSpan  # type: ignore
    from ._models import ModelsAnalyzeResultsDocumentElementsStringField  # type: ignore
    from ._models import ModelsAnalyzeResultsDocumentElementsStyle  # type: ignore
    from ._models import ModelsAnalyzeResultsDocumentElementsTable  # type: ignore
    from ._models import ModelsAnalyzeResultsDocumentElementsTableCell  # type: ignore
    from ._models import ModelsAnalyzeResultsDocumentElementsTimeField  # type: ignore
    from ._models import ModelsAnalyzeResultsDocumentElementsWord  # type: ignore
    from ._models import ModelsDocTypeInfo  # type: ignore
    from ._models import ModelsDocumentFieldSchema  # type: ignore
    from ._models import ModelsModelInfo  # type: ignore
    from ._models import ModelsModelSummary  # type: ignore
    from ._models import OperationsGetOperationResponse  # type: ignore
    from ._models import OperationsOperationInfo  # type: ignore
    from ._models import PageModelsModelSummary  # type: ignore
    from ._models import PageOperationsOperationInfo  # type: ignore
    from ._models import ResourceInfo  # type: ignore

from ._form_recognizer_client_enums import (
    Enum1,
    ModelsAnalyzeResultsAnalyzeOperationStatus,
    ModelsAnalyzeResultsDocumentElementsPageUnit,
    ModelsAnalyzeResultsDocumentElementsSelectionMarkFieldValueSelectionMark,
    ModelsAnalyzeResultsDocumentElementsSelectionMarkState,
    ModelsAnalyzeResultsDocumentElementsSignatureFieldValueSignature,
    ModelsAnalyzeResultsDocumentElementsTableCellKind,
    ModelsBuildMode,
    ModelsDocumentFieldType,
    ModelsStringIndexType,
    OperationsOperationKind,
    OperationsOperationStatus,
)

__all__ = [
    'AzureBlobContentSource',
    'BuildModelRequest',
    'ComponentModelInfo',
    'ComposeModelRequest',
    'CopyAuthorization',
    'CopyAuthorizationRequest',
    'CustomDocumentModelInfo',
    'Error',
    'ModelsAnalyzeRequest',
    'ModelsAnalyzeResultsAnalyzeOperation',
    'ModelsAnalyzeResultsAnalyzeResult',
    'ModelsAnalyzeResultsDocumentElementsArrayField',
    'ModelsAnalyzeResultsDocumentElementsBoundingRegion',
    'ModelsAnalyzeResultsDocumentElementsCountryRegionField',
    'ModelsAnalyzeResultsDocumentElementsCurrencyField',
    'ModelsAnalyzeResultsDocumentElementsCurrencyValue',
    'ModelsAnalyzeResultsDocumentElementsDateField',
    'ModelsAnalyzeResultsDocumentElementsDocument',
    'ModelsAnalyzeResultsDocumentElementsEntity',
    'ModelsAnalyzeResultsDocumentElementsIntegerField',
    'ModelsAnalyzeResultsDocumentElementsKeyValueElement',
    'ModelsAnalyzeResultsDocumentElementsKeyValuePair',
    'ModelsAnalyzeResultsDocumentElementsLanguage',
    'ModelsAnalyzeResultsDocumentElementsLine',
    'ModelsAnalyzeResultsDocumentElementsObjectField',
    'ModelsAnalyzeResultsDocumentElementsPage',
    'ModelsAnalyzeResultsDocumentElementsPhoneNumberField',
    'ModelsAnalyzeResultsDocumentElementsSelectionMark',
    'ModelsAnalyzeResultsDocumentElementsSelectionMarkField',
    'ModelsAnalyzeResultsDocumentElementsSignatureField',
    'ModelsAnalyzeResultsDocumentElementsSpan',
    'ModelsAnalyzeResultsDocumentElementsStringField',
    'ModelsAnalyzeResultsDocumentElementsStyle',
    'ModelsAnalyzeResultsDocumentElementsTable',
    'ModelsAnalyzeResultsDocumentElementsTableCell',
    'ModelsAnalyzeResultsDocumentElementsTimeField',
    'ModelsAnalyzeResultsDocumentElementsWord',
    'ModelsDocTypeInfo',
    'ModelsDocumentFieldSchema',
    'ModelsModelInfo',
    'ModelsModelSummary',
    'OperationsGetOperationResponse',
    'OperationsOperationInfo',
    'PageModelsModelSummary',
    'PageOperationsOperationInfo',
    'ResourceInfo',
    'Enum1',
    'ModelsAnalyzeResultsAnalyzeOperationStatus',
    'ModelsAnalyzeResultsDocumentElementsPageUnit',
    'ModelsAnalyzeResultsDocumentElementsSelectionMarkFieldValueSelectionMark',
    'ModelsAnalyzeResultsDocumentElementsSelectionMarkState',
    'ModelsAnalyzeResultsDocumentElementsSignatureFieldValueSignature',
    'ModelsAnalyzeResultsDocumentElementsTableCellKind',
    'ModelsBuildMode',
    'ModelsDocumentFieldType',
    'ModelsStringIndexType',
    'OperationsOperationKind',
    'OperationsOperationStatus',
]
